### ISSUE TITLE
App crashing after logging in

### ISSUE THREAD

**Issue by sohamc1fm** [thingsboard/flutter_thingsboard_pe_app#1]
After loggin in following error occurs:
`I/flutter ( 6249):   DEBUG │ 🐛 On load finished.
I/flutter ( 6249):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   ERROR │ ThingsboardError: message: [], errorCode: null, status: 404
I/flutter ( 6249):   ERROR │ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:86:18)
I/flutter ( 6249):   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter ( 6249):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:557:28)
I/flutter ( 6249):   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:795:22)
I/flutter ( 6249):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:555:22)
I/flutter ( 6249):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:174:37)
I/flutter ( 6249):   ERROR │ #6      _rootRun (dart:async/zone.dart:1346:47)
I/flutter ( 6249):   ERROR │ #7      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter ( 6249):   ERROR │ #8      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter ( 6249):   ERROR │ #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
I/flutter ( 6249):   ERROR │ #10     _rootRun (dart:async/zone.dart:1354:13)
I/flutter ( 6249):   ERROR │ #11     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter ( 6249):   ERROR │ #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
I/flutter ( 6249):   ERROR │ #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter ( 6249):   ERROR │ #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
I/flutter ( 6249):   ERROR │ #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
I/flutter ( 6249):   ERROR │ #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
I/flutter ( 6249):   ERROR │ 
I/flutter ( 6249):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6249):   ERROR │ #0   toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:86:18)
I/flutter ( 6249):   ERROR │ #1   HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter ( 6249):   ERROR │ #2   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:557:28)
I/flutter ( 6249):   ERROR │ #3   DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:795:22)
I/flutter ( 6249):   ERROR │ #4   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:555:22)
I/flutter ( 6249):   ERROR │ #5   new Future.<anonymous closure> (dart:async/future.dart:174:37)
I/flutter ( 6249):   ERROR │ #6   _rootRun (dart:async/zone.dart:1346:47)
I/flutter ( 6249):   ERROR │ #7   _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter ( 6249):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6249):   ERROR │ ⛔ onError
I/flutter ( 6249):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG │ 🐛 On load started.
I/flutter ( 6249):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false
I/flutter ( 6249):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   DEBUG │ 🐛 On load finished.
I/flutter ( 6249):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6249):   ERROR │ Null check operator used on a null value
I/flutter ( 6249):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6249):   ERROR │ #0   WlService._updateImages (package:thingsboard_app/utils/services/wl_service.dart:263:76)
I/flutter ( 6249):   ERROR │ #1   <asynchronous suspension>
I/flutter ( 6249):   ERROR │ #2   WlService._loadUserWhiteLabelingParams (package:thingsboard_app/utils/services/wl_service.dart:220:7)
I/flutter ( 6249):   ERROR │ #3   <asynchronous suspension>
I/flutter ( 6249):   ERROR │ #4   WlService.updateWhiteLabeling (package:thingsboard_app/utils/services/wl_service.dart:161:7)
I/flutter ( 6249):   ERROR │ #5   <asynchronous suspension>
I/flutter ( 6249):   ERROR │ #6   TbContext.onUserLoaded (package:thingsboard_app/core/context/tb_context.dart:316:7)
I/flutter ( 6249):   ERROR │ #7   <asynchronous suspension>
I/flutter ( 6249):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6249):   ERROR │ ⛔ Error: Null check operator used on a null value
I/flutter ( 6249):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
`

**Comment by vvlladd28** [comment]
Hi @sohamc1fm,
Can write the value of the variable thingsBoardApi Endpoint? If the value is localhost, then replace it with the IP address of your PC.

**Comment by sohamc1fm** [comment]
Hello @vvlladd28 ,
I've already changed the value of thingsBoardApiEndpoint to the server where we've hosted thingsboard PE.

**Comment by sohamc1fm** [comment]
Hello,
Any update on this?

Thank you.

**Comment by ybeshkarov** [comment]
Hello @sohamc1fm,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!
