### ISSUE TITLE
Unable to Receive Alarms in the App

### ISSUE THREAD

**Issue by senshi900** [thingsboard/flutter_thingsboard_pe_app#101]
Hello,
I'm encountering an issue where I'm not receiving alarms within the app. After investigating, I discovered a solution involving the following code snippet:

            ? json['details']
            : null, // Handle if details is not a Map<String, dynamic> to the alarm_model 
This code modification resolves the problem temporarily. However, when sharing the code with other developers, they're unable to observe the changes. Is there a solution to this issue that doesn't involve modifying the model?

Just for your reference, I'm using PE app version 1.1.0. The file where I implemented the changes is located at: "C:\Users\User\AppData\Local\Pub\Cache\hosted\pub.dev\thingsboard_pe_client-1.1.0\lib\src\model\alarm_models".

Thank you.
![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/129005111/20e72ed6-48c9-4a33-b180-40853a73bc8f)

**Comment by ybeshkarov** [comment]
Duplicate https://github.com/thingsboard/dart_thingsboard_pe_client/issues/25
