### ISSUE TITLE
APP loading launch time

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/flutter_thingsboard_pe_app#104]
I noticed on startup the app takes approximately 20+ seconds to load, is there a way for me to debug this process with more granularity as it seems too long, I would like to provide feedback on each stage to the user of the app as to why it's taking long to load or actions that occur in the background. On the web page it loads quite quickly but, on the app, it is much to slow on startup. Any feedback or way to improve this issue would be appreciated (currently building on android but will be building for iOS soon too)

**Comment by ybeshkarov** [comment]
Hi @Mark-MV-Wizard,

Here you can find info about how to debug performance issues https://docs.flutter.dev/perf
