### ISSUE TITLE
iOS Notifications not showing in App

### ISSUE THREAD

**Issue by WillieSpence** [thingsboard/flutter_thingsboard_pe_app#105]
Hi, 

I'm having an issue where the push notifications to iOS is not persisted in the App. The notification pops up on the screen without issues, but when I open the app and go to the notifications, there's nothing there?

This works 100% on Android, however I have a few iOS users that are having this issue. Any ideas?

Regards

**Comment by ybeshkarov** [comment]
Hi @WillieSpence,

Which app version do you use?

**Comment by WillieSpence** [comment]
@ybeshkarov ,

I'm using app version 1.1.0

Connecting to Thingsboard Cloud platform.

**Comment by ybeshkarov** [comment]
@WillieSpence did you build your app manually or download it from a store?

**Comment by WillieSpence** [comment]
Hi. I built it manually from the Git Repository.

**Comment by ybeshkarov** [comment]
Got it, thanks.

Please checkout this branch https://github.com/thingsboard/flutter_thingsboard_pe_app/tree/release/1.1.1 and rebuild your app. 

@WillieSpence

**Comment by WillieSpence** [comment]
@ybeshkarov , noted. Thanks, let me try that and will let you know if everything is sorted. Appreciate your help so far.

**Comment by WillieSpence** [comment]
@ybeshkarov , I am closing this issue. Initial testing that we have done after releasing version 1.1.1 seems that the issue is resolved. Much appreciated for your quick help and assistance. If anything pops up I will log a new issue or re-open this one.
