### ISSUE TITLE
Home button to refresh the default dashboard state

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/flutter_thingsboard_pe_app#107]
For the things board PE flutter app, I want to add home buttons to the nav bar from the app . The current nav bar button only toggles between 'More' , Home , 'Devices' and 'Alarms '. I have a client who requested to add a home button on the Navbar that can basically shortcut to default dashboard. I have successfully hidden the buttons for devices and alarms and am just left with home and more. So instead of interreacting with the WebView , I need the flutter app to change the dashboard state by embedding a flutter nav bar button to go to the home default state. Can I get any assistance in implementing the home button to behave in this way or creating a new button that does that

**Comment by ybeshkarov** [comment]
Hello @Mark-MV-Wizard,

The question you asked is too complicated and will require massive code changes. I cannot say change that and that, because it will not work.
But ThingsBoard has support options. I would recommend considering these options https://thingsboard.io/docs/services/support/
