### ISSUE TITLE
IOS: unable to create a iOS App Development provisioning profile

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/flutter_thingsboard_pe_app#109]
I am preparing to move my thingsboard PE app from android to iOS and I noticed a few issues. 
On the home screen the dashboard does not load on the simulator after logging in. Also I have not been able to provision a device to work using the free developer account to run with xcode as I want to test the app on a real device. Do I need an apple developer paid account (99 dollars one) or can I continue to test on a free tier. I need the device to run on the iPhone that I have I cannot move past these two errors 

Cannot create a iOS app Development provisioning profile for  _________. Personal development teams including "My team name" do not support in-App Purchases and push Notification capabilities.

then the second error is No Profiles for ''bundle identifier" were found. Xcode couldn't find and iOS App Development provisioning profiles matching 'Bundle identifier". 

If fire base is the issue causing the need for a paid development account, am I able to edit the thingsboard PE app such that it does not need to work with firebase

**Comment by ybeshkarov** [comment]
Hello,

This link should be useful https://docs.flutter.dev/deployment/ios.
And if you want to test any app on a a real IOS device, you need a developer account.
