### ISSUE TITLE
Three dots button and user is not able to export data as CSV/Excel in mobile app issue in latest release  

### ISSUE THREAD

**Issue by gaurav36** [thingsboard/flutter_thingsboard_pe_app#110]
There is issue (may be known issue ) with latest version of thingsboard 3.7 with PE Mobile app.

Issue 1: I have disabled everything from Toolbar setting I can see three dots ... on right side of mobile app which does not looks good.

Issue 2: I am not able to export data in the CSV/Exel file, when i click on it then nothing happen.

Is it a known issue or some other configuration i need to do which i missed in the documentation ? Thank you in advance :)

Reproduced video/screenshot:

![Screenshot from 2024-07-10 00-03-12](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/2d29ad83-c9a3-40c9-863e-f17aa89b1fc5)
![181917ea-ac1d-41d7-87cb-c8fff12d8b38](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/8e77d84d-ad27-44ab-af42-a3bcaaf15ca7)

https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/78ee7e50-2896-4a51-94d8-c510ce886974

**Comment by ybeshkarov** [comment]
Hello @gaurav36,

It's duplicate https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/81

**Comment by instorehub1** [comment]
Hello @ybeshkarov  , I see data export part is duplicate but these tree dots issue do you have suggestion ? I disabled all toolbar settings but these three dots that highlighted in the screenshot and visible in the video still coming. do you know how can i hide it ?

**Comment by gaurav36** [comment]
Hello @ybeshkarov   , I see data export part is duplicate but these tree dots issue do you have suggestion ? I disabled all toolbar settings but these three dots that highlighted in the screenshot and visible in the video still coming. do you know how can i hide it ?

**Comment by ybeshkarov** [comment]
It's probably something on your dashboard on the TB level. As in mobile, it's just a web view and on mobile level we don't add any buttons or elements.

@gaurav36

**Comment by gaurav36** [comment]
Hi @ybeshkarov , I see, but i did not added any settings on my dashboard.  I am just simple timeseries card with above  mentioned setting in question screenshot. 
my dashboard looks like following:

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/c0810e12-796c-423b-aaa2-8efa23d80e2e)


and when i click on these three dots on top right corner then it expend:

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/021f5370-c886-4574-9997-686ee409d00a)

do you know where i can turn this off "close toolbar" button ?

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/6826559/fdf7834c-666f-4ae5-99e0-12d8fc100a41)


Problem is with this close toolbar button

**Comment by gaurav36** [comment]
@ybeshkarov , I see, it was toolbar setting that need to be disabled completely. its works fine now. Do you know if you are releasing this data export functionality issue soon in next release ?
