### ISSUE TITLE
State not working in Notification Click

### ISSUE THREAD

**Issue by ronit18** [thingsboard/flutter_thingsboard_pe_app#114]
In my android flutter app. I am receiving notification perfectly. In that notification template, I have given a dashboard state to go when notification is clicked. And in that state i have given all widgets 'Entity from dashboard state'. 
![image](https://github.com/user-attachments/assets/263ef3a6-c65d-457f-99e7-8caa4faacf52)

Now this is working perfectly (going in that state with the selected device) when i click and open notification through pop-up notifications. But when i try to do the same from notification menu in app. It is going in that state but not with the entity.

![ss-1](https://github.com/user-attachments/assets/e1b68fa7-a016-4c36-9a3f-5def0de8d2f4)

And then i tried to print this state, So I added a log.debug in `lib/core/context/tb_context.dart`

![ss-2](https://github.com/user-attachments/assets/0508b0f4-ac9a-4292-9d56-a444797059af)

But this is not printing the state in debug console...

![ss-3](https://github.com/user-attachments/assets/b48a3ab6-27a0-4633-9c17-dd4710c4c8c7)

**Comment by ronit18** [comment]
Any Update?

**Comment by ybeshkarov** [comment]
Hello @ronit18,

I see an issue in the way you're using longing. 

![350663039-b48a3ab6-27a0-4633-9c17-dd4710c4c8c7](https://github.com/user-attachments/assets/0d526a90-bf2a-4558-8add-b5516e8ecff7)

Please see the screenshot above. You passed the `state` argument as an error, that's why you see a stack trace and dashboard state separately, from the message you created.

Here is the method signature 
<img width="673" alt="Screenshot 2024-08-01 at 12 26 47" src="https://github.com/user-attachments/assets/d3b74ab3-41a9-4179-8489-69caa0462ea8">

**Comment by bhaveshgohel** [comment]
Hi @ybeshkarov it seems @ronit18 having issue when he try to click the notification from  notification tab in app. Main issue is It is going in that state **but not with the entity**.

eg.
WORKING:  Notification popsup in the mobile.. > Open by clicking it from mobile lockscreen. it works
NOT WORKING: Open the same notificaiton from inside the application notifiction tab.. it open the state but not with entity. ( i.e device details dashboard  state with specific device)

How to solve this?

**Comment by ybeshkarov** [comment]
You need to debug an app to see which data you receive in both cases and compare. 
Based on it you can decide what to do next.

**Comment by bhaveshgohel** [comment]
We have used the [same code](https://github.com/thingsboard/flutter_thingsboard_pe_app/blob/9f54c1232c1a8a4a6921ba8a3eddf603cb51f90f/lib/core/context/tb_context.dart#L31) from this Repo . It supposed to work as intended. :confused: 
Can you share snippet or reference how we can navigate on click with state and entity from notification tab?

Thank you.

**Comment by ybeshkarov** [comment]
`NotificationService` has the `handleClickOnNotification` method. This method is used everywhere through the app to handle notification clicks.

**Comment by bhaveshgohel** [comment]
@ybeshkarov. Thank you for the quick reply.  Let's us check notification_service code and implimentation internally and update you the findings. :+1:

**Comment by ybeshkarov** [comment]
Hello guys,

Is it still relevant?
