### ISSUE TITLE
Zeitenstellfenster passt nicht in iOS App

### ISSUE THREAD

**Issue by Tomi05-k** [thingsboard/flutter_thingsboard_pe_app#115]
Hey hello, I have the problem that the dashboard time window is not displayed correctly. It disappears on the right side.

Best regards Tom! 
![IMG_5896](https://github.com/user-attachments/assets/651df6f1-f5b5-45d1-83cd-be60c0fac5a0)

**Comment by WillieSpence** [comment]
This is same as reporting on #47 , please refer to that issue for work-around.
