### ISSUE TITLE
flutter_thingsboard_app works on IOS17.6 but flutter_thingsboard_pe_app doesn't

### ISSUE THREAD

**Issue by PhilipRai** [thingsboard/flutter_thingsboard_pe_app#119]
There seems to be a difference between these to master versions.

With the PE_APP im get a infinity waiting loop upon pressing a dashboard and I the interface becomes unresponsive.

The PE_APP works great on the simulator with IOS17.5

**Comment by ybeshkarov** [comment]
Hello,

As far as I understand mobile app it's ThingsBoard Cloud downloaded from a store and PE_APP is an app you've created from the source code. Am I right?

**Comment by PhilipRai** [comment]
[flutter_thingsboard_pe_app](https://github.com/thingsboard/flutter_thingsboard_pe_app)

and 

[flutter_thingsboard_app](https://github.com/thingsboard/flutter_thingsboard_app)

**Comment by ybeshkarov** [comment]
You build your app from the `master` branch on this repository and your dashboards are not loading?

**Comment by PhilipRai** [comment]
Yup! not working on IOS 17.6 public Beta

**Comment by ybeshkarov** [comment]
For your app did you use the PE backend?

**Comment by PhilipRai** [comment]
Haven't changed anything except for the things that were needed. (bundleID, version, images etc)

I can see it's not only on that specific IOS version, but also other lower versions which can't open the dashboard via TestFlight.

But still, it works great on the simulator.

**Comment by ybeshkarov** [comment]
I may suggest implementing a change mentioned in the comment there https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/113#issuecomment-2245037727
But you still may have some issues with dashboards on IOS. 

Or just wait until this issue is fixed, it must be the next release.

**Comment by PhilipRai** [comment]
I just tried with a IOS device connected via USB and it has no problem launching/building and working on that same device

**Comment by PhilipRai** [comment]
If it's launched as `flutter run` (in debug mode) then the dashboard works

But

If  use `flutter run --release` then it doesn't

**Comment by ybeshkarov** [comment]
Yeap, I know :) That's why I refer you to a specific comment in my message above. There is described the same what's you found.

**Comment by PhilipRai** [comment]
Voila! That did the trick for now. Thanks
