### ISSUE TITLE
How to add a mobile action for reading NFC tags?

### ISSUE THREAD

**Issue by technorabilia** [thingsboard/flutter_thingsboard_pe_app#12]
In the ThingsBoard PE Mobile Application there are different mobile actions available like e.g. scan QR code.
https://thingsboard.io/docs/pe/mobile/mobile-actions/

We would like to add a mobile action for reading NFC tags. How should we proceed?

**Comment by technorabilia** [comment]
Any input on how we should approach this? If I am not mistaken we also not only need to change the mobile app, but also ThingsBoard itself to add a mobile action for NFC?

Feedback is appreciated.

**Comment by ybeshkarov** [comment]
Hello @technorabilia,

Quick googling leads me to this plugin which may help you. But that's not all and more changes will require definitely. I'm not ready to say what else.
But you may consider ThingsBoard support options https://thingsboard.io/docs/services/support/ to receive a complex answer or a ready solution.

Best Regards.
