### ISSUE TITLE
Push notifications are not working with V3.63PE

### ISSUE THREAD

**Issue by patobalbi** [thingsboard/flutter_thingsboard_pe_app#120]
Hello,

Can you help me?

the app is working but I cannot make the push notifications to work. I configured the web server we have according to the documentation, however in V3.6.3 I don't have the option mentioned. Is it necessary to update?

**From documentation:**
![image](https://github.com/user-attachments/assets/f5cc410b-a78c-4202-ad58-00722fa752ff)

**On my instance (I don't have the checkbox), the key is uploaded:**
![image](https://github.com/user-attachments/assets/903fd06c-e5dc-4a85-9b02-96d4b754d5fe)

**I followed these steps (1 and 2) as mentioned in the documentation:**

![image](https://github.com/user-attachments/assets/9e5ba748-dea3-42a0-910e-c7901c519d61)

**I receive an exception with iOS** 

![image](https://github.com/user-attachments/assets/637e63be-d033-4046-8e0b-a781af723182)

**This is my firebase_options.dart file. Is it correct?**

                        `// File generated by FlutterFire CLI.
                        // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
                        import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
                        
                        /// Default [FirebaseOptions] for use with your Firebase apps.
                        ///
                        /// Example:
                        /// ```dart
                        /// import 'firebase_options.dart';
                        /// // ...
                        /// await Firebase.initializeApp(
                        ///   options: DefaultFirebaseOptions.currentPlatform,
                        /// );
                        /// ```
                        class DefaultFirebaseOptions {
                          static FirebaseOptions get currentPlatform {
                            throw UnsupportedError(
                              'Firebase have not been configured - '
                              'you can reconfigure this by running the FlutterFire CLI again.',
                            );
                          }
                        }`
                        \

**In firebase website seems to be correct**

![image](https://github.com/user-attachments/assets/20838778-aa74-4a62-86b6-b1912247f796)

**This is my phone:**
![image](https://github.com/user-attachments/assets/330011d1-53f3-42ce-b0f7-c25c7989c045)

**This is the platform when I try to send a notification**
![image](https://github.com/user-attachments/assets/5cd1e97b-aad9-412d-88ee-65e0530d25ff)

Thanks!

**Comment by ybeshkarov** [comment]
Hello,

The `firebase_options.dart` has not been configured properly. Seems it's connected with the Unsupported error you have received for IOS. I never saw such an error before, but you can try to delete `firebase_options.dart` and run `flutterfire configure` again. Hope it will help.
