### ISSUE TITLE
Release version in iOS fail touch

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/flutter_thingsboard_pe_app#13]
Hi all,

When i do a relased build in real devide, the touch in dasboard dont work.

The icons at the bottom works. any idea?

Thanks!

**Comment by Apxllyxn** [comment]
I am having the same issue for days ! 
I've tried many thing but no avail !

**Comment by ybeshkarov** [comment]
HI @Ataraxiall ,

I'll close it as a lot of time has passed, but if it's still relevant for you feel free to reopen.
