### ISSUE TITLE
Data Communication issue between flespi and thingsboard

### ISSUE THREAD

**Issue by adarsh23590** [thingsboard/flutter_thingsboard_pe_app#135]
We have install thingsboard community edition on our linux server. We already have an account in flespi which contains all our teltonika devices. Flespi is working fine. Now we need to integrate thingsboard for our end users. We have set our Linux server address with port 1883 in secondary GPRS settings in Flespi. We have already setup Stream and assign it to all devices so that all data can transmit via stream to thingsboard on our server. Now We are facing some issue as below

- Once i remove all devices from thingsboard platform and if refresh the page. then it is not adding devices from flespi automatically. I have to make test device on platform and then need to add its access token to flespi stream. Then after it is sending devices
- Telemetry data is also sometimes not working as real-time data. Sometimes old data is showing on map or any other widget like speedometer , battery level, etc.

So can anyone help me to resolve this issue.

**Comment by ybeshkarov** [comment]
Hello @adarsh23590,

It seems your question is not related to the mobile app itself, but the ThingsBoard platform. Am I right?

**Comment by adarsh23590** [comment]
Yes it is related to thingsboard platform

**Comment by ybeshkarov** [comment]
Could you then recreate the issue there, please? https://github.com/thingsboard/thingsboard/issues
