### ISSUE TITLE
Error when scanning the QR code with the message HandshakeException: Handshake Error

### ISSUE THREAD

**Issue by mde2017** [thingsboard/flutter_thingsboard_pe_app#136]
Error when scanning the QR code with the message HandshakeException: Handshake Error (see attached screenshot)

First assumption was: SSL certificate chain must be set up for ThingsBoard.
After consultation with our IT infrastructure, it would now be important to know how the app establishes the connection to ThingsBoard Web and what is required for the connection. ThingsBoard Web is located behind the firewall, which is unknown to the app; the proxy handles the allocation.
Data that the app tries to exchange is intercepted.

Can you tell how to overcome this issue? 

![error_message](https://github.com/user-attachments/assets/fdcbb2de-b8c6-444d-a7f9-a1cf0dee3183)

**Comment by ybeshkarov** [comment]
Hello @mde2017,

Something is wrong with the TB configuration, but not the mobile app itself. Could you add details on how to reproduce it? To which TB instance you're trying to log in?

**Comment by ybeshkarov** [comment]
Well, honestly the communication is pretty straightforward. It's just HTTP requests like GET, POST, etc. Nothing special not happening between mobile and TB communication. 

Not sure it will be useful for you but we using this package for it https://pub.dev/packages/dio.

For me, it looks like something is wrong with the SSL certificate you have on the TB instance you trying to log in. But it's just an assumption. 

@mde2017
