### ISSUE TITLE
several problems in the source code of release 1.2.0 & java.util.zip.ZipException

### ISSUE THREAD

**Issue by MichaelKerscher** [thingsboard/flutter_thingsboard_pe_app#140]
Hi,

a) If I open the Flutter project from the master branch in VS code, I get 12 errors, 2 warnings and 27 infos (mostly about obsolete elements that should no longer be used). - Is this occurrence known?

![image](https://github.com/user-attachments/assets/1c9f1181-08e6-4d5e-8d55-5a6603b9b5d8)

b) When building despite the error messages, I get a java.util.zip.ZipException:
![image](https://github.com/user-attachments/assets/f2023a9c-bb04-4a89-94b1-3ecc0cd60c75)

According to my research, the distributionUrl in the project directory in gradle-wrapper.properties is incorrect. I cannot find the archive gradle-7.5.1-all.zip in MVN REPOSITORY. After the Gradle version 7.4.x comes 8.0.x:
![image](https://github.com/user-attachments/assets/acb504e8-11c5-4869-b592-87704268cf98)

Am I right?

Best regards!

**Comment by ybeshkarov** [comment]
Hello, which version of Flutter did you use?

**Comment by MichaelKerscher** [comment]
Thanks for your quick response!

I use Flutter 3.24.2 - channel stable and Dart 3.5.2 and DevTools 2.37.2

**Comment by ybeshkarov** [comment]
The master or release/1.2.0 branch works with Flutter 3.19.6. For newer flutter brings an issue during the building process.

**Comment by MichaelKerscher** [comment]
Ok, thank you!

So i have downgraded Flutter to 3.19.6 - Dart 3.34 and DevTools 2.31.1.

Only after flutter run I still get the java.util.zip.ZipException: 
![image](https://github.com/user-attachments/assets/0c6bb023-04cc-4742-a30c-ebe87003517e)
(The screenshot also shows the remaining problems after git checkout 3.19.6.)

Can you imagine how the java.util.zip.ZipException occurs and how it can be eliminated?

**Comment by ybeshkarov** [comment]
Never seen this before. Did you mange to resolve it?

**Comment by MichaelKerscher** [comment]
No, unfortunately not. The only thing I have found out so far is that it works on my private computer. There I really only have to download the source code of release 1.2.0 and can execute it in VS code. Only at work I get this problem with the java.util.zip.ZipException: invalid block type.

**Comment by MichaelKerscher** [comment]
I have now been able to rectify the error. 
Solution: 
- Completely uninstalled Android Studio.
- Android Studio Hedgehog 2023.1.1 reinstalled
