### ISSUE TITLE
Cannot click anything on Home page

### ISSUE THREAD

**Issue by Apxllyxn** [thingsboard/flutter_thingsboard_pe_app#15]
I can scroll but i cannot click anything on the dashboard on the Home page
The other 4 buttons on the bottom appbar works tho
Also the problem only occurs in the Home page but not other pages

This only happens in iOS release build, everything works fine on debug mode

**Comment by Ataraxiall** [comment]
Your server connections must be https for ios. 
or enable NSAllowsArbitraryLoads  
https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by ybeshkarov** [comment]
HI @sagarbp,

I'll close it as a lot of time has passed, but if it's still relevant for you feel free to reopen.
