### ISSUE TITLE
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by UIT-Manh** [thingsboard/flutter_thingsboard_pe_app#153]
I'm having problem version 1.2.0
![error](https://github.com/user-attachments/assets/51df4f33-9da0-4d0f-b364-72e3042cfe94)
My flutter version: 
![flutter](https://github.com/user-attachments/assets/21099678-a018-4614-a144-85089dcae0da)

**Comment by ybeshkarov** [comment]
1. The warning from the first screenshot has a link you can click on to read more. Those errors don't influence the build process. 
2. To build a release or master branch, use flutter 3.19.6.

**Comment by UIT-Manh** [comment]
Is it ok if I use another flutter version?

**Comment by UIT-Manh** [comment]
I fixed the above error but it shows many errors below.
![image](https://github.com/user-attachments/assets/46e063ab-1eeb-4b8c-ae3f-f35e92e99cc6)
![image](https://github.com/user-attachments/assets/3f781f4a-50c0-49f1-9f9c-a69ae8d79936)

**Comment by ybeshkarov** [comment]
> Is it ok if I use another flutter version?

nope, it's not. I can guarantee with the flutter 3.19.6 stable channel you will be able to build the project. 
But cannot guarantee the same for other versions. And definitely, it will not work with the flutter 3.24.2 you have.

**Comment by UIT-Manh** [comment]
I install flutter 3.19.6 but still error verison:
![image](https://github.com/user-attachments/assets/ec891956-1a3a-4e9c-b180-d4e06c3cea1b)

**Comment by ybeshkarov** [comment]
It's not an error. Seem build is successfully completed based on this message `Launching lib\main.dart on Nokia 8 1 in debug mode...`.

**Comment by eticialima** [comment]
> Eu instalei o flutter 3.19.6 mas ainda dá erro na versão: ![image](https://github.com/user-attachments/assets/ec891956-1a3a-4e9c-b180-d4e06c3cea1b)

Estou com mesmo problema não consegui resolver.

**Comment by EAbeier** [comment]
Same error here, i've already change my graddle.settings and my Build.graddle

![Image](https://github.com/user-attachments/assets/542fe082-a92b-40e0-8290-535ad80e055b)
