### ISSUE TITLE
flutter_thingsboard_pe_app-release-1.1.1 problem config

### ISSUE THREAD

**Issue by rantherz** [thingsboard/flutter_thingsboard_pe_app#159]
![problema things](https://github.com/user-attachments/assets/548958e1-bcfe-4ca8-b720-6dad7ed826

i have this problem after install flutter_thingsboard

**Comment by ybeshkarov** [comment]
Which one?

**Comment by rantherz** [comment]
this one 
https://postimg.cc/XGqqXkZ2

**Comment by rantherz** [comment]
can you help me, and i have other question.
 for implement push notification i have to use 
flutter_thingsboard_pe_app-release-1.1.1  or i can implemenet push notification in the thingsboard aplication .

https://ibb.co/Dw0bdm9

**Comment by ybeshkarov** [comment]
> this one https://postimg.cc/XGqqXkZ2

Seems you have changed the version of flutter_inappwebview. The fix is pretty straightforward. Just change Uri to WebUri.

Push notifications are already implemented in the 1.1.1. There is a link with details https://thingsboard.io/blog/push-notifications-to-thingsboard-mobile-apps/

**Comment by rantherz** [comment]
https://ibb.co/yprTG5X

now i got this bug. how i can  fix that.

**Comment by ybeshkarov** [comment]
It's not a bug, just try to google it.
