### ISSUE TITLE
Info.plist error extra info about

### ISSUE THREAD

**Issue by ribera01** [thingsboard/flutter_thingsboard_pe_app#16]
I will deploy ios app

Error: An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
No se pudo instalar “ThingsBoard PE App”

**Comment by ybeshkarov** [comment]
HI @ribera01,

I'll close it as a lot of time has passed, but if it's still relevant for you feel free to reopen with additional description.
