### ISSUE TITLE
Type UiApplication error on IOS

### ISSUE THREAD

**Issue by valixkaldor** [thingsboard/flutter_thingsboard_pe_app#160]
I upgraded Xcode to the latest version yesterday and now my app will not build or launch on IOS.
I am getting the error message that Url application does not conform to protocol launcher.
I have already attempted to update the URL_Launcher_IOS to current release and it has not worked.
![b9325792-d62b-4e14-a8f1-fa160081f9ee](https://github.com/user-attachments/assets/ee85afa1-d611-4fc9-a908-079654bf84a7)

**Comment by ybeshkarov** [comment]
Hello, it's the issue with Xcode 16. Do what's described in the comment there https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221#issuecomment-2348119737
It will resolve the issue. 

@valixkaldor

**Comment by valixkaldor** [comment]
thanks. i got it to work
