### ISSUE TITLE
WebView not loading in IOS

### ISSUE THREAD

**Issue by valixkaldor** [thingsboard/flutter_thingsboard_pe_app#161]
I am trying to connect to my things board dashboard in order to load my widgets.
On android the full thing is loading but on IOS none of the widgets from the WebView is loading. there is just a continuous loading symbol.
![1727423847038](https://github.com/user-attachments/assets/536ef708-9134-4826-963d-2d3b2c5865e9)

**Comment by ybeshkarov** [comment]
Hello,

The issue will be fixed in the 1.3.0 mobile release and as soon as the ThingsBoard platform is released.

**Comment by valixkaldor** [comment]
is there no work around that I can use for v1.2.0. I would prefer to not have to redo all of the customisation and additional features that I added to my app

**Comment by ybeshkarov** [comment]
Unfortunately no. You going to face the issue regularly on the IOS for 1.2.0. 

As an option, you can try merging your changes with the 1.3.0 release.

**Comment by valixkaldor** [comment]
ok thank you

**Comment by valixkaldor** [comment]
@ybeshkarov 
is this the version in which the webview is working.
https://github.com/thingsboard/flutter_thingsboard_pe_app/releases/tag/v1.3.0

i was looking through past issues and i think that this issue came up before here: https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/113

**Comment by valixkaldor** [comment]
I just tried using v1.3.0. The same error is still persisting.
I can login with my username/password however the dashboard WebView does not load on IOS.
I am fairly confident that the issue with the source code since this time I only changed my endpoint (no additional customisation)

**Comment by ybeshkarov** [comment]
> as soon as the ThingsBoard platform is released.

The ThingsBoard platform has not been released yet.

**Comment by valixkaldor** [comment]
Thanks for the clarification.
Do you have any idea when the thingsboard platform will be updates - so i know when i should resume IOS Dashboard testing on the project

**Comment by valixkaldor** [comment]
Hi @ybeshkarov 
Which version of the Thingsboard platform are you referring to.
We are currently using 3.6.4
Can you also please specify the root cause of the issue as I will need to be specific when I inform my clients.

**Comment by ybeshkarov** [comment]
> Thanks for the clarification. Do you have any idea when the thingsboard platform will be updates - so i know when i should resume IOS Dashboard testing on the project

Week or two I hope, but cannot be sure.



> Hi @ybeshkarov Which version of the Thingsboard platform are you referring to. We are currently using 3.6.4 Can you also please specify the root cause of the issue as I will need to be specific when I inform my clients.

ThingsBoard 3.8.0. The loading dashboards it's about open web view and mobile/front end communication. This is the platform fix https://github.com/thingsboard/thingsboard/pull/11326

**Comment by PhilipRai** [comment]
Just upgraded to TB 3.8.0 and with mobile PE 1.3.0 I get the same failure. Eternal spinning wheel upon choosing a dashboard.

**Comment by ybeshkarov** [comment]
Some dashboards load longer than others; this may be an issue for you. 

The communication flow between mobile and platform is follows
1. Waiting for `tbMobileReadyHandler`. (log output `Invoked tbMobileReadyHandler`)
2. Then mobile must call `postWebMessage` with type `openDashboardMessage`
3. Then the mobile dashboard must appear

Unfortunately, I cannot debug the code locally in your environment, so hope this will help you.

**Comment by valixkaldor** [comment]
I also have the same issue.
i was just able to upgrade my thingsboard version however, the eternal spinning wheel of death wont leave my Android app - which is still working on my 1.2 version of the app.

getting the following messages:

WaitForGcToComplete blocked ProfileSaver on NativeAlloc for 54.903ms
I/ngsboard.pe.app( 1019): NativeAlloc concurrent copying GC freed 48KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 4882KB/9764KB, paused 6.582ms,129us total 71.374ms
I/ngsboard.pe.app( 1019): NativeAlloc concurrent copying GC freed 62KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 4883KB/9767KB, paused 168us,63us total 104.769ms
I/ngsboard.pe.app( 1019): Waiting for a blocking GC ProfileSaver
I/ngsboard.pe.app( 1019): WaitForGcToComplete blocked ProfileSaver on NativeAlloc for 51.727ms
I/ngsboard.pe.app( 1019): Waiting for a blocking GC ProfileSaver
I/ngsboard.pe.app( 1019): WaitForGcToComplete blocked ProfileSaver on NativeAlloc for 41.447ms

**Comment by ybeshkarov** [comment]
Yes, this is because you're using 3.6.4. You can try with thingsboard.cloud to be sure everything works for you.

**Comment by valixkaldor** [comment]
Thanks.
Got it working on IOS today.
used app v1.3 and thingsboard v3.8.1
