### ISSUE TITLE
1.3.0 build failure

### ISSUE THREAD

**Issue by PhilipRai** [thingsboard/flutter_thingsboard_pe_app#163]
Since App Store keeps rejecting the 1.1.0 version im trying to build a new app...

Trying now with version 1.3.0
Upon building the app I get this:
`Error (Xcode): lib/core/context/tb_context.dart:57:26: Error: Can't declare a member that conflicts with an inherited one.`

[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale da-DK)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (5 available)            
[✓] Network resources

**Comment by ybeshkarov** [comment]
Hello,

https://github.com/thingsboard/flutter_thingsboard_pe_app/releases/tag/v1.3.0

> We now officially support Flutter version 3.22.x

**Comment by PhilipRai** [comment]
So far so good. Didn't see that note :)

But I can't really build it.

I get:

`/Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'nanopb' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'OrderedSet' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseMessaging' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseInstallations' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseCoreInternal' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'nanopb-nanopb_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'flutter_local_notifications-flutter_local_notifications_privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'PromisesObjC-FBLPromises_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'PromisesObjC' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'MTBBarcodeScanner' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'GoogleUtilities-GoogleUtilities_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'GoogleDataTransport-GoogleDataTransport_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseMessaging-FirebaseMessaging_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseInstallations-FirebaseInstallations_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseCoreInternal-FirebaseCoreInternal_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseCore-FirebaseCore_Privacy' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'FirebaseCore' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'GoogleUtilities' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'GoogleDataTransport' from project 'Pods')
    /Users/philipraistrick/flutter_thingsboard_pe_app-master1.3/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0,
    but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'Firebase' from project 'Pods')`

**Comment by ybeshkarov** [comment]
It's Xcode 16 issue, 
just do what's mentioned in those two tickets

https://github.com/firebase/flutterfire/issues/12962#issuecomment-2183898535
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221#issuecomment-2348119737

**Comment by PhilipRai** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:FABF432C-0590-4BEA-9672-DDD528C2B7C9, OS:17.5, name:iPhone 15 }
    { platform:iOS Simulator, id:FABF432C-0590-4BEA-9672-DDD528C2B7C9, OS:17.5, name:iPhone 15 }
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/88/_76r050x4_j838d0rp7j1xb40000gn/T/flutter_tools.K0fJmu/flutter_ios_build_temp_dir8i0Cvl/temporary_xcresult_bundle

**Comment by PhilipRai** [comment]
Never mind its fixed...

**Comment by ybeshkarov** [comment]
Glad to help!
