### ISSUE TITLE
App wont connet to Personal server due to bad certficicates

### ISSUE THREAD

**Issue by DoctorWho786** [thingsboard/flutter_thingsboard_pe_app#166]
Is there a way that I can get my app to connect to my secure server instance of thing board without the proper certificates. currently my ssl certificate is self-signed and the app will not connect.

Alternatively and preferably, is there a way that i can take my certificates and add them to the app so that it can communicate with the server.

**Comment by ybeshkarov** [comment]
Hello,

You can do the same I post there https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/164#issuecomment-2399522173
