### ISSUE TITLE
Unsupported Version

### ISSUE THREAD

**Issue by lucaslpmoura** [thingsboard/flutter_thingsboard_pe_app#167]
When I log in with my credentials, the app displays the following message:

![image](https://github.com/user-attachments/assets/ee0183a0-301c-4fdf-8800-4480ba130eaa)

This is a fresh build, and i have changed the endpoint to my application. I've tested it on the desktop build (Linux) and on an android emulator.

**Flutter**: 3.24.3
**App**: 1.3.0

**Comment by ybeshkarov** [comment]
Hello,

Mobile release 1.3.0 works with ThingsBoard v3.8.0. That's why you see this message.

**Comment by royoarnaud** [comment]
Hello,
According to your documentation (https://thingsboard.io/docs/pe/mobile/getting-started/), the Mobile release 1.3.0 is compatible with ThingsBoard 3.6.3PE and above, correct?

![Capture d'écran 2024-10-09 102659](https://github.com/user-attachments/assets/fdd08610-83f7-4418-9ce2-a4b11a1b5e82)

**Comment by ybeshkarov** [comment]
Not really. Documentation is wrong and will be fixed. 
Mobile release 1.3.0 is compatible only with the 3.8.0 platform version.
