### ISSUE TITLE
hi i have a problem with push notificatios.

### ISSUE THREAD

**Issue by rantherz** [thingsboard/flutter_thingsboard_pe_app#169]
When the alarm is generated, I do not receive the push notification as such, it is only displayed if I open the thingsboard application.

https://ibb.co/RCVtxtB

I want to receive the notification as I receive it in the mail see next image: https://ibb.co/wzXxGjR

I guess the problem is in the chain of rules:https://ibb.co/2MSPJs2

**Comment by wouterdejonggit** [comment]
Hi, 

Try this reply: https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/178#issuecomment-2440942946
