### ISSUE TITLE
Android QUERY_ALL_PACKAGES permission

### ISSUE THREAD

**Issue by luiscubilla** [thingsboard/flutter_thingsboard_pe_app#17]
The app requires use of the QUERY_ALL_PACKAGES permission, Google play console require to provide a description and short video of the core feature in the app that requires this permission. 

What feature of thingboard require this permission?

**Comment by ybeshkarov** [comment]
Hello @luiscubilla,

the QUERY_ALL_PACKAGES is not used anymore. 

Best Regards.
