### ISSUE TITLE
Unable to Sign in to Mobile App

### ISSUE THREAD

**Issue by WillieSpence** [thingsboard/flutter_thingsboard_pe_app#175]
Hi.

Since today, I'm unable to sign into my Thingsboard Mobile App. I did notice there were maintenance ongoing, but after maintenance window still unable to login in.

My app very briefly logs in and then logs me out saying session has expired.

I'm running version 1.2.0 of the Mobile App against ThingsBoard Cloud

Were there breaking changes or something during maintenance that causes the app to break?

Regards
Willie

**Comment by ybeshkarov** [comment]
Hello,

Please try one more time. I just checked with 1.2.0 and all good for me.

**Comment by WillieSpence** [comment]
Hi.
Unfortunately still same issue for me. I haven't made any changes to my app in the last 4 months. Only suddenly today it start giving this issue and many of my customers are complaining as well with same issue.

Sometimes I get Unauthorised once I log in and other times session expired.

I can log in fine via the Thingsboard Cloud portal. Its only the Mobile App seems to give this issue.

**Comment by Tomi05-k** [comment]
Same problem for me. 
No login possible after the update to ThingsBoard 3.6.0. 
Also problems with the public dashboards.  
Here is the issue:
Public Dashboard access-forbidden since Update 3.8.0 #11836

**Comment by ybeshkarov** [comment]
Could you provide a screenshot or a screen recording with an issue where you cannot login? @Tomi05-k

**Comment by WillieSpence** [comment]
@ybeshkarov , just to update from my side. Yesterday I spent upgrading our app to 1.3.0. Tested fine on both Android and iOS simulators and have just released the IPA on the Apple App store. So far so good, this seems to have resolved the issue for my iOS users. I'm just waiting for Google Play to release / approve the app for distribution then hopefully the Android customers will also be resolved. 

So it seems something to do with 1.2.0 of the mobile app and the latest version of the thingsboard cloud platform that caused the issue...

Will keep this thread posted once the 1.3.0 is released on Google App store.

**Comment by Tomi05-k** [comment]
oke all clear 👍🏼
I'll give that a try too. 
But do you also have problems with opening public dashboards?

**Comment by WillieSpence** [comment]
Nope, unfortunately I don't have any public dashboards, only private dashboards that I share via dashboard groups.

**Comment by leorenan** [comment]
> @ybeshkarov , just to update from my side. Yesterday I spent upgrading our app to 1.3.0. Tested fine on both Android and iOS simulators and have just released the IPA on the Apple App store. So far so good, this seems to have resolved the issue for my iOS users. I'm just waiting for Google Play to release / approve the app for distribution then hopefully the Android customers will also be resolved.
> 
> So it seems something to do with 1.2.0 of the mobile app and the latest version of the thingsboard cloud platform that caused the issue...
> 
> Will keep this thread posted once the 1.3.0 is released on Google App store.

I'm having the same problem and I've already published it to my android clients and it's still giving me the same error
It's been fixed for iOS and a new bug has been introduced for Android
Could you share the versions of flutter, Xcode, pod, android sdk?

**Comment by ybeshkarov** [comment]
@leorenan did you use the latest 1.3.0 mobile release?

**Comment by leorenan** [comment]
@ybeshkarov 

I'm using version 1.3.0. I've even just received a rejection from Google in the review reporting the same problem.
Could you share the versions of flutter, xcode, por and ide Android you're using as well, to try and help in some way.

**Comment by ybeshkarov** [comment]
It could be that the dart client just cached for you and you facing this issue. 
Run this command to clean the cache pub dependencies you have. 
`dart pub cache clean`

Not sure how it helps, but
- The officially supported flutter for 1.3.0 is 3.22 so I use this version
- Xcode 15.4
- pod 1.15.2
- Android Studio Hedgehog | 2023.1.1 Patch

**Comment by ybeshkarov** [comment]
Is it still actual?

**Comment by leorenan** [comment]
@ybeshkarov 

I'm still having the same problem, practically all Samsung phones are having the same problem even when updating to 1.3.0
The problem started happening after the update of the thingsboad cloud platform

**Comment by ybeshkarov** [comment]
In the `pubspec.yaml` change `thingsboard_client: ^1.3.1` to `thingsboard_client: 1.3.1`. This requires dart to use exactly this version of the thingsboard client, then run `flutter clean` and rebuild your project.
