### ISSUE TITLE
Push notification not in notification overview or popup

### ISSUE THREAD

**Issue by wouterdejonggit** [thingsboard/flutter_thingsboard_pe_app#178]
Hi all,

With some efforts I have gotten the Thingsboard Mobile PE version running including notifications. The notifications arrive in the application itself, but they do not create an alarm signalling sound or pop up.

I have checked my notification settings and they do not block the app. I have also tried the Thingsboard Cloud application and this seems to have the same issue. 

Am I missing something on my phone? Or are notifications in the android notification centre not supported on 1.3.1?

Kind regards,
Wouter

**Comment by rantherz** [comment]
i have the same problem...

**Comment by rantherz** [comment]
I think this issue is caused by this Firebase update. Maybe we can fix it by updating the code.

see this url:
https://ibb.co/0j5XPg3

**Comment by ybeshkarov** [comment]
Hello, just checked for Android and iOS and I'm able to get notification sounds, popups, etc.
I guess it might be something wrong with the Firebase configuration on your end.

**Comment by wouterdejonggit** [comment]
Hey ybeshkarov,

thanks for the reply. I've retried the total step by step guide, but I'm getting the exact same results. I've added some screencaps, perhaps I'm overlooking something?

**Firebase Project** (and uploaded payment details for Google Firebase)
![image](https://github.com/user-attachments/assets/c0f42554-f895-4c76-b43c-2886302a9256)

**Key is uploaded in settings/notification**
![image](https://github.com/user-attachments/assets/3cb86eda-814a-4876-84a7-04ad78d1800f)

**Flutterfire configured (with the same Firebase project)**
![image](https://github.com/user-attachments/assets/853f2d93-558b-420d-bd67-334db486451a)

**google-services.json is made**
![image](https://github.com/user-attachments/assets/7c94d142-c479-4b44-a217-550f38c80804)

Still, in the app 'notifications' is grayed out. 'The popup gives me: Notifications are not configured. Please contact your system administrator.'

**Comment by ybeshkarov** [comment]
Hey, 

Please check if your `lib/firebase_options.dart` changed (the name is highlighted in blue).
If not remove this file and run` flutterfire configure` once again. 
I noticed sometimes this script doesn't update that.

**Comment by wouterdejonggit** [comment]
Hey ybeshkarov,

Thanks! This was the issue!

I've ran in some (perhaps newby) issues which are fixed now. Perhaps it is nice to add this to the manual? Or as a trouble shooting guide? Apparently the IDE doesn't perfectly handle all packages.
 
_**If you download Flutter you get 3.24. Users should switch to 3.22.**_ 
Open terminal and Navigate to the flutter location
`cd <flutter_path>
then
`git checkout 3.22
then to make sure it works
`flutter doctor -v`

**_target of uri doesn't exist flutter_gen/gen_l10n/messages.dart_**
Apparently if flutter_gen is in pubspec.yaml, Basically the intl package generates localisation code under a fake flutter_gen package, but there is also a real flutter_gen package on pub.dev. from https://stackoverflow.com/questions/64574620/target-of-uri-doesnt-exist-packageflutter-gen-gen-l10n-gallery-localizations
Option 1: restart IDE
Option 2: remove flutter_gen from pubspec.yaml and then flutter clean

_**If notification is grayed out in the app**_ 
Please check if your lib/firebase_options.dart changed (the name is highlighted in blue).
If not remove this file and run flutterfire configure once again.

**Comment by ybeshkarov** [comment]
Cool!

It might be a good idea but I need to think about how to implement it, thank you!
