### ISSUE TITLE
configuration problem.

### ISSUE THREAD

**Issue by rantherz** [thingsboard/flutter_thingsboard_pe_app#180]
Configuration issue. I don't know why I have this error in the code. I was trying to solve it, but I can't find the solution.

imagen in this url:
https://ibb.co/9p2mhys

**Comment by MichaelKerscher** [comment]
I get the same error:
_The class 'TbContext' cannot define the field 'onPopInvoked' and have a method 'PopEntry.onPopInvoked' with the same name. Try converting the getter to a method or rename the field to a name that doesn't cause a conflict._

The error occurs with Flutter 3.19.6 as well as with Flutter 3.24.6.
With Flutter 3.24.6 I also use Dart 3.5.3 and DevTools 2.37.3 and work in the stable channel.

**Comment by ybeshkarov** [comment]
It's because you're using a non-supported Flutter version. Here, you can find more about which version you need: https://github.com/thingsboard/flutter_thingsboard_pe_app/releases/tag/v1.3.0.

**Comment by MichaelKerscher** [comment]
Ah ok, thanks. I didn't know that it is recorded which Flutter version is required in each case.

It has now helped me to use Flutter version 3.22.0. 

However, I have not yet integrated FVM. I'm still used to git checkout 3.22.0 and it works.

**Comment by ybeshkarov** [comment]
It's okay, FVM just for your convenience.
