### ISSUE TITLE
How do i disable the dashboard popup on login (I want to go directly to the home tab)

### ISSUE THREAD

**Issue by DoctorWho786** [thingsboard/flutter_thingsboard_pe_app#181]
In version 1.2 of the app we were able to use this code in the main.dart file to prevent the dashboard from poping up on login:

home:
            // TwoPageView(
            //   controller: _mainPageViewController,
            //   first:
            MaterialApp(
          key: mainAppKey,
          scaffoldMessengerKey: appRouter.tbContext.messengerKey,
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: S.delegate.supportedLocales,
          title: wlParams.appTitle!,
          theme: data,
          themeMode: ThemeMode.dark,
          darkTheme: tbDarkTheme,
          onGenerateRoute: appRouter.router.generator,
          navigatorObservers: [appRouter.tbContext.routeObserver],
        ),
        // second: MaterialApp(
        //   key: dashboardKey,
        //   // scaffoldMessengerKey: appRouter.tbContext.messengerKey,
        //   localizationsDelegates: [
        //     S.delegate,
        //     GlobalMaterialLocalizations.delegate,
        //     GlobalWidgetsLocalizations.delegate,
        //     GlobalCupertinoLocalizations.delegate,
        //   ],
        //   supportedLocales: S.delegate.supportedLocales,
        //   title: wlParams.appTitle!,
        //   theme: data,
        //   themeMode: ThemeMode.light,
        //   darkTheme: tbDarkTheme,
        //   home: MainDashboardPage(appRouter.tbContext,
        //       controller: _mainDashboardPageController),
        // ),
      ),
      //),

Now in 1.3 things have changed quite a bit and i would like some help to make the home page our default login screen

**Comment by ybeshkarov** [comment]
Hello @DoctorWho786,

If I understand correctly you have a home or default dashboard selected for your user. That's why you see some dashboard instead of a dashboard grid by default.

**Comment by DoctorWho786** [comment]
Yes.
I wanted to change the code so that even if there is a default exists the app will ignore it.
It will not create the two page view dashboard with the appbar with the backbutton on top.
instead it will just show the home page with the nav bar at the bottom.

**Comment by ybeshkarov** [comment]
Okay, I see.

In `lib/core/context/tb_context.dart`
Change from
<img width="761" alt="Screenshot 2024-10-23 at 15 05 14" src="https://github.com/user-attachments/assets/9518ef3d-1971-4c55-8604-7d508090500f">
to
<img width="761" alt="Screenshot 2024-10-23 at 15 05 40" src="https://github.com/user-attachments/assets/ac508b3e-3763-45a7-a7ba-7df9b13f5e8e">

and in` lib/modules/home/home_page.dart`
change from 
<img width="928" alt="Screenshot 2024-10-23 at 15 06 19" src="https://github.com/user-attachments/assets/b5e4c4af-6cf0-48dd-a40e-67dbd2da130b">
to
<img width="928" alt="Screenshot 2024-10-23 at 15 06 27" src="https://github.com/user-attachments/assets/a4e25e52-b734-40f1-9e60-0cd64b73119d">

**Comment by DoctorWho786** [comment]
Thank.
I tried it out, but it is still not working.

Instead, it says route not defined: /main.

I also tried /home but that just made my home page show all of the dashboards available to my user as thumbnails

**Comment by ybeshkarov** [comment]
Hold on, let me see.

**Comment by ybeshkarov** [comment]
My bad, `/main` route is from my custom branch.
I've created a branch for you disable-dashboards. Please check it out and update me if it resolves your question.

**Comment by DoctorWho786** [comment]
Thanks for all of your help.

It is working.
I ended up keeping the home page.dart as is. since i wanted the dashboard to be build as home.
