### ISSUE TITLE
Navigation to another dashboard from custom action doesn't work in mobile app

### ISSUE THREAD

**Issue by irrtc-admin** [thingsboard/flutter_thingsboard_pe_app#190]
We have an entity table in a dashboard where a custom action is invoked on row click. In this custom action, we are navigation the user to another dashboard using dashboard id. This action is successful in the browser Web app and the new dashboard opens in the same window. However, this action doesn't work from the iOS version of the mobile app. We see the error shown in the screenshot below:

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-30 at 17 13 23](https://github.com/user-attachments/assets/5d0ab2f2-82a0-4683-95a2-24352fd0ae8d)

This is the custom action code:

let target_dashboard_id = "Admin Dashboard ID" in additionalParams.entity ? additionalParams.entity["Admin Dashboard ID"] : null;

if (target_dashboard_id !== null ) {
    let stateObject = {
        id: "customer_details_view",
        params: {
            entityId: entityId,
            entityName: entityName
        }
    };
    
    let state = objToBase64URI([stateObject]);
    let url = "/dashboards/" + target_dashboard_id + "?state=" + state + "";
    widgetContext.router.navigateByUrl(url);
}

function objToBase64URI(obj) {
    return encodeURIComponent(objToBase64(obj));
}

function objToBase64(obj) {
    const json = JSON.stringify(obj);
    return btoa(encodeURIComponent(json).replace(
        /%([0-9A-F]{2})/g,
        function toSolidBytes(match, p1) {
            return String.fromCharCode(Number('0x' +
                p1));
        }));
}

Has anyone encountered this and/or know how to solve it? I am assuming it is something to do with the url, but I am not sure what. Thanks in advance.

**Comment by ybeshkarov** [comment]
Hey, 

I've created branch for you https://github.com/thingsboard/flutter_thingsboard_pe_app/tree/dashboard-navigation.
Please check if it's what you looking for.

**Comment by irrtc-admin** [comment]
> Hey,
> 
> I've created branch for you https://github.com/thingsboard/flutter_thingsboard_pe_app/tree/dashboard-navigation. Please check if it's what you looking for.

@ybeshkarov thank you this fix worked! Appreciate your help!
