### ISSUE TITLE
Trendz widgets on ThingsBoard PE are not working on the Mobile App

### ISSUE THREAD

**Issue by sagarbp** [thingsboard/flutter_thingsboard_pe_app#20]
I have a ThingsBoard PE server, and I use it along with Trendz Analytics as well. There are some widgets on my ThingsBoard PE which use Trendz visualizations but when I log in on the Mobile App, I cannot see those visualizations. 

It just says "Widget Error: TypeError: jwtToken.replaceAll is not a function" 

How do I go about solving this issue? Any help would be great, thanks!

**Comment by ybeshkarov** [comment]
HI @sagarbp,

I'll close it as a lot of time has passed, but if it's still relevant for you feel free to reopen.
