### ISSUE TITLE
Self Registration flow

### ISSUE THREAD

**Issue by jsobieski** [thingsboard/flutter_thingsboard_pe_app#24]
When self registering from the mobile PE app the user is created but the activation email won't work but when self registering from the web it succeeds.  I narrowed it down that when I get the activate email after signing up on the mobile app it sends the below API link to activate.  When I register via the web it sends same API but does not include the optional pkgName parameter.   I also tested this in Swagger and it does appear that the API call fails when I include the pkgName.  Wondering if anyone else has experienced this and found a work around?  I submitted a ticket with Thingsboard as well as I assume this API might have an issue accepting the pkgName unless I'm missing something else.

[:443/api/noauth/activateEmail?emailCode=qu3TkHiFpvnoErc6WO01U50BVGcVaM&pkgName=santafe.telkonet.app']

**Comment by ybeshkarov** [comment]
Hello @jsobieski,

Is it still relevant?
