### ISSUE TITLE
How do you change the logo when you open the app?

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/flutter_thingsboard_pe_app#25]
How do you change the logo when you open the app?

![image](https://user-images.githubusercontent.com/108116747/207211738-0e799596-a9a1-474e-9a77-7556cdf46523.png)

I was only able to change the loading logo that comes after this.

**Comment by Anmirazik** [comment]
hi , have you found the solutions ?

**Comment by ybeshkarov** [comment]
Hello @rajSilikon, @Anmirazik,

The splash screen for Android is configured in android/app/src/main/res. In the screenshot, you can see the thingsboard.png files labeled in blue. If you replace these files with your images, you will see your custom splash screen.

<img width="363" alt="Screenshot 2024-05-28 at 15 23 01" src="https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/10604455/95172c20-d8e6-45e3-8b5f-ff8f638c00e9">

For more details on configuring the splash screen, refer to these resources:

[Flutter Android Splash Screen](https://docs.flutter.dev/platform-integration/android/splash-screen)
[Android Developer Splash Screen](https://developer.android.com/develop/ui/views/launch/splash-screen)
