### ISSUE TITLE
Unable to connect 'thingsboard.cloud'

### ISSUE THREAD

**Issue by ockum12** [thingsboard/flutter_thingsboard_pe_app#26]
I got a ERROR messge.  
I/flutter (12221):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (12221):   ERROR │ ⛔ Error: ThingsboardError: message: [Unable to connect], errorCode: 2, status: null
I/flutter (12221):   ERROR │ ⛔ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter (12221):   ERROR │ ⛔ #1      HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter (12221):   ERROR │ ⛔ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter (12221):   ERROR │ ⛔ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
I/flutter (12221):   ERROR │ ⛔ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter (12221):   ERROR │ ⛔ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
I/flutter (12221):   ERROR │ ⛔ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter (12221):   ERROR │ ⛔ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter (12221):   ERROR │ ⛔ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter (12221):   ERROR │ ⛔ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
I/flutter (12221):   ERROR │ ⛔ 
I/flutter (12221):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
My app_constants.dart is
abstract class ThingsboardAppConstants {
  static final thingsBoardApiEndpoint = 'https://thingsboard.cloud';
                                  
  static final thingsboardOAuth2CallbackUrlScheme ='org.thingsboard.pe.app.auth';

  /// Not for production (only for debugging)
  static final thingsboardOAuth2AppSecret = '';

  /// Not for production (only for debugging)
  static final thingsboardSignUpAppSecret = '';
}

Do I need more setup on 'thingsboard.cloud'?

**Comment by ezeroldan24** [comment]
I have the same problem, did you find a solution?

**Comment by JuliusHarald** [comment]
Any updates on this?
