### ISSUE TITLE
unauthorised and session expired

### ISSUE THREAD

**Issue by BluRanger** [thingsboard/flutter_thingsboard_pe_app#27]
I am getting below error saying unauthorized for the first time and later session expired. I am providing right credentials. 

I/flutter ( 4917):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 4917):   ERROR │ ThingsboardError: message: [Unauthorized!], errorCode: null, status: null
I/flutter ( 4917):   ERROR │ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 4917):   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter ( 4917):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter ( 4917):   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
I/flutter ( 4917):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter ( 4917):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
I/flutter ( 4917):   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter ( 4917):   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter ( 4917):   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter ( 4917):   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
I/flutter ( 4917):   ERROR │ 
I/flutter ( 4917):   ERROR

**Comment by salemsw** [comment]
I have exactly the same error

**Comment by Seungkoo** [comment]
I also have the same problem.

**Comment by ezeroldan24** [comment]
I have the same problem, did you find a solution?

**Comment by Seungkoo** [comment]
I found the solution of this problem. 
API and model might be changed from ThingsBoard platform version 3.4.2. "Asset_profile" model was added and this change was applied to dart package "thingsboard_pe_client" v1.0.5.
Open  the file "pubspec.yaml" in your project directory and change the version of thingsboard_pe_client from 1.0.4 to 1.0.5, recompile your project.

**Comment by salemsw** [comment]
Thank you very much @Seungkoo, it works.

**Comment by ezeroldan24** [comment]
Thank you very much, it works fine @Seungkoo .

**Comment by badril1978** [comment]
works for me as well.

**Comment by ezeroldan24** [comment]
Does anyone know if there is a way to prevent this from happening again with new updates? Thank you.

**Comment by BluRanger** [comment]
probably someone from thingsboard team has to take a pick and change the version on the pubsepec file may be... probably not sure how the development process is in thingsboard.

**Comment by BluRanger** [comment]
thanks @Seungkoo  its working fine !! but how come you know this ?
