### ISSUE TITLE
How to disable zoom in graph to change Dashboard Time Window?

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/flutter_thingsboard_pe_app#30]
![tb](https://user-images.githubusercontent.com/108116747/213610489-4bb11894-eb7d-45c1-9de9-131997add565.png)

How to disable zoom in graph to change Dashboard Time Window?

When ever user clicks on the graph and move the cursor it selects that portion and will change the dashboard time window.

Good feature for web user interface.
How ever when using this on my mobile phone.
While scrolling and when your finger hits the graph. it causes it to change dashboard time window.

so its a bit annoying for our customer.
How do we disable this feature?

**Comment by ybeshkarov** [comment]
Hi @rajSilikon,

Is it a mobile-related question? As I see on the screenshot you provided it looks like a platform itself.
Am I right?
