### ISSUE TITLE
windows build is failing for this app with out any error

### ISSUE THREAD

**Issue by BluRanger** [thingsboard/flutter_thingsboard_pe_app#31]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Exception: Build process failed.

**Comment by BluRanger** [comment]
@ashvayka @ikulikov @Backdraft007 @vvlladd28  can someone please help me here or this is not possible ?

**Comment by Backdraft007** [comment]
@BluRanger,
there have to be some more information in your log files. Your current informations are not enough to say something.

**Comment by BluRanger** [comment]
@Backdraft007 , even i am bit confused because there is nothing on the terminal except that the build failed...! any idea that i can get a verbose log of the build ??
