### ISSUE TITLE
App stays on the loading screen forever

### ISSUE THREAD

**Issue by Maxwh21** [thingsboard/flutter_thingsboard_pe_app#32]
When I set the endpoint to the demo account the app works fine, when I change it to my endpoint it stays on the loading screen forever

**Comment by yunamoon** [comment]
Hi. I'm having a similar problem. In my case, I can't access the dashboard. Did you find a solution?

**Comment by Maxwh21** [comment]
Not yet but i feel like it could have something to do with the version of thingsboard being used

**Comment by vvlladd28** [comment]
Hi @Maxwh21 and @yunamoon
We are very sorry that you received this error. We have already updated the code in the **master branch** and fixed this problem.
