### ISSUE TITLE
Dashboards not implemented on Mobile Application

### ISSUE THREAD

**Issue by lbrogan1** [thingsboard/flutter_thingsboard_pe_app#33]
How do I get the dashboards attached to device profiles from the web version of ThingsBoard to the mobile application?  

<img width="409" alt="not_imp_image" src="https://user-images.githubusercontent.com/109886134/217081188-898d39bb-f01c-4ef9-a7c0-9eed049afda0.png">

**Comment by yunamoon** [comment]
Hi. I'm having a similar problem. Did you find a solution?

**Comment by ronald-cr** [comment]
I've it only on the web built. Deployed on Android it's working fine.

**Comment by ybeshkarov** [comment]
Hello @lbrogan1,

The web is not supported that's why you see this message.
