### ISSUE TITLE
flutter inwebview not available

### ISSUE THREAD

**Issue by yunamoon** [thingsboard/flutter_thingsboard_pe_app#37]
Hi, I am using things board pe flutter app. 

I finally found the error part. 

There seems to be a security issue with the flutter in webview. Is there anything else I need to set up?

[<img width="340" alt="스크린샷 2023-02-27 오후 6 31 53" src="https://user-images.githubusercontent.com/78346017/221526734-539a5edf-1b93-4519-b157-9b16b35be818.png">
](url)

**Comment by ybeshkarov** [comment]
Hello @yunamoon,

I will close this issue since a significant amount of time has passed since your initial query. However, if the issue is still relevant, please feel free to reopen it and provide additional information, such as the mobile app console output.

Thanks!
