### ISSUE TITLE
How to optimized webview load in dashboard?

### ISSUE THREAD

**Issue by keval-devani** [thingsboard/flutter_thingsboard_pe_app#38]
App is taking too much time to load data in dashboard in home page of app. Is there anyway to reduce time to load data?

**Comment by ybeshkarov** [comment]
Hello @keval-devani,

I recommend adding logs or using Flutter devtool to measure what is causing the delay. Determine if it's due to network conditions or another factor. Once you collect some data and identify the bottleneck, you can consider performance improvements.

Thanks.
