### ISSUE TITLE
App stopped working after updating the thingsboard to PE 3.4.4

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/flutter_thingsboard_pe_app#43]
App stopped working after updating the thingsboard to PE 3.4.4

![image](https://user-images.githubusercontent.com/108116747/229431938-8016aaff-b6aa-4372-921d-2a88b086d9fd.png)

**Comment by ybeshkarov** [comment]
Hello @rajSilikon.

This issue is no longer relevant to you, am I right?
Please reopen this ticket with details in case not.
