### ISSUE TITLE
Can't Sign into app after 3.5.0 upgrade

### ISSUE THREAD

**Issue by daniq350** [thingsboard/flutter_thingsboard_pe_app#45]
I could not sign into the app after upgrading things board from version 3.4.4 to 3.5.0 PE. There is an issue with the dart client library.

**Comment by DouglassSpencer** [comment]
I have the same problem. In my case, when I try to log in, the app returns the message "unauthorized"

**Comment by daniq350** [comment]
@holgerkoch, not yet. Downgraded to the previous version. Hope they will update the flutter/dart code in some time.

**Comment by daniq350** [comment]
@holgerkoch @DouglassSpencer I saw some changes in the repo 18 hours ago.

**Comment by daniq350** [comment]
![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/12201316/133343e1-f5e7-4e3d-8839-296f0af041ac)

**Comment by holgerkoch** [comment]
Hi,
with the latest source code, it is possible to login again. Unfortunatelly, now the layout is corrupted and the app is useless.

Best regards, Holger
