### ISSUE TITLE
Error running "flutter run"

### ISSUE THREAD

**Issue by Kneidl18** [thingsboard/flutter_thingsboard_pe_app#53]
When i try to run "flutter run", i get the error message:
Error (Xcode): lib/core/auth/signup/privacy_policy.dart:52:27: Error: No named parameter with the name 'tagsList'.

Running on macOS with newest flutter and dart installed, trying to run on iPhone simulator for iPhone12-iOS 17.
How can i fix this?

**Comment by ybeshkarov** [comment]
Hello @Kneidl18!

Are you still facing this issue?

**Comment by ybeshkarov** [comment]
Closed due to lack of response. Please reopen if the issue is still relevant to you.

@Kneidl18.
