### ISSUE TITLE
Infinite Loading Screen -App is Broken

### ISSUE THREAD

**Issue by macso-philipperivard** [thingsboard/flutter_thingsboard_pe_app#55]
Hi,

I'm running into a critical issue with this app. When I login to the app, I see a spinning loader that is stuck there forever. I haven't made any changes to the app and I'm using the 1.0.7 version from the master branch. I've tried all other versions and none are working.

I'm using thingsboard.cloud which seems to be 3.6.1PAAS

This is very worrying as it seems to render the app completely useless.

Thanks

**Comment by ybeshkarov** [comment]
Hello @macso-philipperivard!

You mentioned you haven't made any changes, but you need to change the ThingsBoard endpoint [as mentioned there in Step 3. ](https://thingsboard.io/docs/pe/mobile/getting-started/). 

Please do it and try again :)

**Comment by macso-philipperivard** [comment]
I have done that already of course. If you actually run this app on your system you will notice the same issue as I notice.

**Comment by ybeshkarov** [comment]
It works well for me. 

Could you please provide the following details? 

**Platform type and version (CE, PE, or Cloud with corresponding version; DB type)
**Deployment type and hosting OS
**Steps to reproduce 
**Code/client used to achieve the result (with payload example, auth type)
**The desired behavior of the platform or, basically, the user story
**The nature of the question and end goals you have in mind
**Modifications or custom code done

@macso-philipperivard.
