### ISSUE TITLE
Navigation Card Widget Not Working in PE Mobile Application

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/flutter_thingsboard_pe_app#57]
I have used Navigation cards in my ThingsBoard PE dashboard, and they function correctly on the desktop. However, in the ThingsBoard PE mobile application, the navigation cards are displayed, and upon clicking, they show the properties of the clicked item, but they do not navigate to the desired path. How can I resolve this issue? I'm encountering the same problem on both Android and iOS.

**Comment by ybeshkarov** [comment]
Hi @Faheem-Punnasseri!

Thank you for noticing this. I have addressed the issue in this PR https://github.com/thingsboard/flutter_thingsboard_pe_app/pull/77
