### ISSUE TITLE
Delete account button

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/flutter_thingsboard_pe_app#58]
Good morning, in the ThingsBoard Live app, within the profile, there is the option to delete the account. I find it very useful as it is a requirement from Apple and Google currently to publish the app. However, I don't see it implemented in the GitHub code. Could you let us know if it is possible to add it?

Maybe @ikulikov can help?

Many Thanks

**Comment by ybeshkarov** [comment]
Hello @Ataraxiall!

You can create your own delete button by using the delete API at http://demo.thingsboard.io/swagger-ui/#/sign-up-controller/deleteTenantAccountUsingDELETE.

Here's the process:
- Add a Delete button on the profile page.
- Modify` thingsboard_pe_client` -> `signup_service.dart`.
- Add a method to call the delete API.
