### ISSUE TITLE
Not able to change the thingsboard Icon

### ISSUE THREAD

**Issue by vsood97** [thingsboard/flutter_thingsboard_pe_app#60]
I tried changing the images in the assets. also the checksum but for some reason I still see the old icons. Can anyone help me out with this issue or has anyone managed to fix this yet

**Comment by hayschan** [comment]
Did you build successfully? I can't build the app in both VS Code and Android Studio https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/59

**Comment by vsood97** [comment]
Yes ! the build was successful the app is running as well. Check the version or your app. Is it compatible with your subscription.

**Comment by hayschan** [comment]
Thanks a lot. I have solved the issue already. It is due to network issue.

**Comment by hayschan** [comment]
I managed to change the icon. Here is what I did.

1. Add different resolutions of `custom_logo.png` in `\flutter_thingsboard_pe_app\android\app\src\main\res`. You should put them in folders with the prefix of `mipmap`. I used this Flutter icon [generator](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) to prepare my icons. 
![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/25737801/74e82cc5-eac6-4360-855e-6a78ce107e9e)

2. Go to line 30 of file `flutter_thingsboard_pe_app\android\app\src\main\AndroidManifest.xml`. Change         `android:icon="@mipmap/launcher_icon">` to `android:icon="@mipmap/custom_logo">`.
https://github.com/thingsboard/flutter_thingsboard_pe_app/blob/e3574bc36e4914a54eeeb7057d9b99eb67f6d302/android/app/src/main/AndroidManifest.xml#L30

I hope it helpsee.

**Comment by vsood97** [comment]
Hey Thanks a lot man ! It worked
