### ISSUE TITLE
Loading Screen with Thingsboard Icon

### ISSUE THREAD

**Issue by vsood97** [thingsboard/flutter_thingsboard_pe_app#61]
I can't seem to disable or change the loading screen which has the thingsboard icon. Is there a way to do so?

**Comment by ybeshkarov** [comment]
Hello @vsood97.

The ThingsBoard loading indicator consists of two assets.
1. `assets/images/thingsboard_center.svg`
2. `assets/images/thingsboard_outer.svg`

You can substitute these assets with your own or completely modify the screen by altering the TbProgressIndicator class.
