### ISSUE TITLE
How do I configure push notifications for alarms?

### ISSUE THREAD

**Issue by ronald-cr** [thingsboard/flutter_thingsboard_pe_app#62]
Maybe it's not possible. But it would be very cool if the user could see alarms as push notifcations. Additionally with a counter on the app icon when user has open alarms.
Is such a feature planned for future versions?

**Comment by ronald-cr** [comment]
Maybe this will be addressed by [PR](https://github.com/thingsboard/flutter_thingsboard_pe_app/pull/64)
... would be perfect for me ;)

**Comment by ybeshkarov** [comment]
Hello @ronald-cr!

Push notifications are planned for the upcoming release, exactly with the PR you mentioned. But will not have the ability to open an alarm so far.

We will address this feature in future releases.
