### ISSUE TITLE
ThingsBoard PE mobile app: Functionality issues on Android & iPad

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/flutter_thingsboard_pe_app#63]
I'm encountering an issue where the ThingsBoard PE mobile application doesn't work on Android and iPad, but functions normally on iPhone. Does anyone have insights or solutions for this problem?

**Comment by ybeshkarov** [comment]
Hello @Faheem-Punnasseri!

Could you please provide more details about what isn't working for you?

**Comment by Faheem-Punnasseri** [comment]
Thank you for the response. Actually, when opening the app, it only displays a loading action with the logo and does not proceed any further on Android and iPad devices. However, it is working fine on the iPhone.

**Comment by ybeshkarov** [comment]
There may be an issue with your backend configuration, as https://thingsboard.cloud/ works well for me.

https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/10604455/11fa5fa3-6509-4ece-977e-0f34efc35caf


Are there any outputs from the app in your terminal or IDE? If so, could you please attach them?

**Comment by Faheem-Punnasseri** [comment]
Thanks, @ybeshkarov. The issue has been fixed now. We have just rebuilt the development file, and it is now working perfectly.
