### ISSUE TITLE
Why does my customers see all Device Profiles?

### ISSUE THREAD

**Issue by inanlia** [thingsboard/flutter_thingsboard_pe_app#69]
My customers can see the device profiles that normally only I should see. 
Even though these device profiles show 0 devices they should not be able to see them at all.
For context my TB version is 3.5.1 and mobile app was created when latest version was 3.5. If this issue was resolved please forgive my lack of information.

**Comment by KamranArain** [comment]
This issue still exist even in 3.8.0 version of TB. even with PE version of TB mobile app had to manually work on to only show the devices incase of user and show all profiles in case of admin.

**Comment by ybeshkarov** [comment]
Appreciate your input,

In the next release, the issue will be fixed.
