### ISSUE TITLE
App permission 

### ISSUE THREAD

**Issue by ronald-cr** [thingsboard/flutter_thingsboard_pe_app#70]
Hi, I new in Flutter. But I'm wondering about the permissions. E.g. for android following permissions are required.
`
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
`
If I understood the usecase of that app right only INTERNET, CAMERA, WRITE_EXTERNAL_STORAGE should be enough? Is that an error or is a documentation existing why this permissions are needed?
Thanks a lot!

**Comment by ybeshkarov** [comment]
Hi @ronald-cr!

Those permissions are necessary as they allow you to configure various behaviors for your dashboards. 
However, if it seems overwhelming for your case, you might consider removing unnecessary permissions and recompiling the app.
