### ISSUE TITLE
Error Encountered When Sending Push Notifications via Notification Center

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/flutter_thingsboard_pe_app#73]
I tried sending notifications(push notification) using the **Notification center** for the **mobile app**. However, when I attempt to send the notifications, I encounter an error (Status code: 401). Can anyone help me with this issue? Additionally, if there are any examples available, that would be helpful.

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/92074733/36ecbd8b-9a0a-46a9-aca1-47fa0eaede87)

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/92074733/c5e17e54-c93a-4fc2-b156-b47562be54b1)

![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/92074733/3618afcf-26a9-4c24-ba67-ff6b29ef242f)

**Comment by ybeshkarov** [comment]
Hi @Faheem-Punnasseri!

Based on your Firebase screenshot, it appears the APNs auth key is not set. Could you please add it? You can find more details here [Upload your APNs authentication key](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key)

**Comment by Faheem-Punnasseri** [comment]
Hi @ybeshkarov 

Thank you for bringing this to my attention. I will ensure that the APNs auth key is added promptly. I appreciate your guidance and will refer to the provided link for more details.

**Comment by ybeshkarov** [comment]
Thank you for bringing this up. We will update the "Get Started" documentation soon for better clarity.
