### ISSUE TITLE
Login page input fields not visible in Dark Mode

### ISSUE THREAD

**Issue by msinphilpk** [thingsboard/flutter_thingsboard_pe_app#8]
The input fields (username and password) in login page is invisible in Dark mode. It is selectable and shows the field on selection. Login button and all other elements are visible. In Light mode, there is no problem.
<img width="450" alt="login_page_in_dark mode" src="https://user-images.githubusercontent.com/22269123/155926839-219556af-50ee-42c4-b074-6df67083c187.png">
<img width="450" alt="login_page_in_light_mode" src="https://user-images.githubusercontent.com/22269123/155926851-23d99b98-e169-4ad9-bdbc-b828bd343420.png">

**Comment by rajSilikon** [comment]
I'm facing the same problem? Have you solved the issue?

**Comment by rajSilikon** [comment]
I am able to login and view the dashboard, my only issue is 
1. Dark mode does not work
2. Change the Logo that appears on loading screen 

![image](https://user-images.githubusercontent.com/108116747/207201656-f33eed91-6ecd-45e3-a59a-b56d1c591f9d.png)

**Comment by ybeshkarov** [comment]
HI all,

I'll close it as a lot of time has passed, but if it's still relevant for you feel free to reopen.
