### ISSUE TITLE
Push Notifications Are Not Configured

### ISSUE THREAD

**Issue by YuriYabe** [thingsboard/flutter_thingsboard_pe_app#93]
Hi, I have the 3.6.3PE version of Thingsboard. I have downloaded all the packages to create the application, and everything works fine except for push notifications, just like in the previous versions.

I followed the guide to integrate Firebase with Flutter to enable push notifications. I built an APK to test it. By going to the app's permissions, I can actually enable the notifications (previously I couldn't even see them). I enabled them, logged in, and checked that the dashboard, alarms, etc., work, and everything is functioning correctly. At this point, I did a notification check.

I went to "More," clicked on "Notifications," and I get the message "Notifications are not configured. Please contact your system administrator" (light gray button).

I inserted the JSON into Thingsboard
I executed flutterfire configure
Followed the documentation
How can I resolve this?
![Immagine WhatsApp 2024-05-16 ore 15 59 33_4fe3e27c](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/158387078/280b91dc-1d20-47bb-9986-ce27c5a3a159)
![777](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/158387078/13a5b046-57e2-40c0-8e44-7e4e94b60fe9)
![Screenshot 2024-05-16 160039](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/158387078/24219e7d-5503-4f1c-8bf3-2cf17bd5fbbd)

**Comment by ybeshkarov** [comment]
Hello @YuriYabe!

After running `flutterfire configure`, you should see changes in `lib/firebase_options.dart`. Can you confirm if you are seeing these changes?

**Comment by YuriYabe** [comment]
Hi @ybeshkarov  , thanks for your response! Yes, I see the changes. Actually, I managed to resolve it during the night. I deleted the firebase_options file and when I did flutterfire configure, it recreated it correctly! I see the notifications now.

However, as soon as I open the app, I get a message "path '/api/notifications/unread/count': not found." I can close it, but it appears every time I reopen the app! In fact, I can't see the unread notifications. Do you have any idea what the problem might be? Tonight I will try to rebuild the app from scratch!

(At least the notifications arrive; if I go under "all" I can see them. The problem is only with the "unread" ones.)

**Comment by YuriYabe** [comment]
> Hi @ybeshkarov , thanks for your response! Yes, I see the changes. Actually, I managed to resolve it during the night. I deleted the firebase_options file and when I did flutterfire configure, it recreated it correctly! I see the notifications now.
> 
> However, as soon as I open the app, I get a message "path '/api/notifications/unread/count': not found." I can close it, but it appears every time I reopen the app! In fact, I can't see the unread notifications. Do you have any idea what the problem might be? Tonight I will try to rebuild the app from scratch!
> 
> (At least the notifications arrive; if I go under "all" I can see them. The problem is only with the "unread" ones.)

UPDATE: (Now I still have the same error, but when I go to "unread" I can see the notifications.)

**Comment by ybeshkarov** [comment]
Hi @YuriYabe,

It's good to hear that the notifications are working for you now.

The error message `path '/api/notifications/unread/count': not found` indicates that your ThingsBoard instance doesn't have the specified endpoint https://thingsboard.cloud/swagger-ui/#/notification-controller/getUnreadNotificationsCountUsingGET.

This endpoint was added in version 3.6.4.

**Comment by ybeshkarov** [comment]
Closed due to no further action required. Please reopen if the issue persists.
