### ISSUE TITLE
In iOS, after login, the application only loads when the user has no assigned dashboard

### ISSUE THREAD

**Issue by solano-juanjo** [thingsboard/flutter_thingsboard_pe_app#96]
**Problem Summary**
The issue occurs for users logging in from an iOS device. After login, the dashboard does not load in most cases, and the application remains stuck loading indefinitely. The first time the user logs in, the dashboard appears correctly, but upon closing and reopening the application, the issue persists.

**Problem Description**

- Observed Behavior:

First login: The dashboard loads correctly.
Reopening the application: Upon closing and reopening the application, the dashboard fails to load, and the application remains stuck loading indefinitely.

- Additional Details:

Affected platform: iOS
Related functionality: Notifications
Notification status:
On Android: They work correctly.
On iOS: They work, but there are issues with the dashboard loading.

**Possible Cause**
This problem started occurring after configuring notifications in the application. While notifications work correctly on both operating systems, the dashboard loading issue only occurs on iOS.

**Steps to Reproduce**
1. Install the application on an iOS device.
2. Log in for the first time and verify that the dashboard loads correctly.
3. Close the application.
4. Reopen the application and log in again.
5. Observe that the application remains stuck loading indefinitely.

**Question**
What could be the explanation for the dashboard failing to load on iOS after configuring notifications?

Any help or suggestions to resolve this issue would be greatly appreciated.

**Comment by ybeshkarov** [comment]
Hello @solano-juanjo!

Thank you for the detailed description. We are aware of this issue and are actively working on a fix.

**Comment by solano-juanjo** [comment]
Hi ybeshkarov,

I was hoping that the latest update would solve this problem but it didn't. At least, I haven't been able to make it.

**Comment by Sekiro-kost** [comment]
Hey @ybeshkarov , I had a similar problem, you closed the issue with your last update to fix it, but it still doesnt work unfortunately

**Comment by ybeshkarov** [comment]
Hello all,

Please recheck this issue with the 1.3.0 release. 

@solano-juanjo @Sekiro-kost

**Comment by Sekiro-kost** [comment]
When I tried a few days ago with your PR 1.3.0, before the merge, I had lots of dependency compatibility problems, ios18, Swift problems etc.

**Comment by ybeshkarov** [comment]
It's an issue with Xcode 16, not the IOS 18 or something. You need to add what's described in the comment there https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221#issuecomment-2348119737


Xcode 15.x works fine.

**Comment by Sekiro-kost** [comment]
> It's an issue with Xcode 16, not the IOS 18 or something. You need to add what's described in the comment there [pichillilorenzo/flutter_inappwebview#2221 (comment)](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221#issuecomment-2348119737)
> 
> Xcode 15.x works fine.

Yes sorry, I meant Xcode, not IOS

Thx for your reply, I will try tomorrow to build your new version
